# Generated by Django 2.2.4 on 2019-08-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=200)),
                ('description_text', models.CharField(max_length=2000)),
                ('author_text', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
